version: '3.7'

services:

  api:
    build:
      context: .
      dockerfile: build/api/Dockerfile
    container_name: gifmachine-api
    environment:
      - RACK_ENV=development
      - GIFMACHINE_PASSWORD=gif-magic
      - DATABASE_URL=postgres://postgres:postgres@gifmachine-db:5432/gifmachine
    ports:
      - 8080:4567
    networks:
      - gifmachine-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12.2-alpine
    container_name: gifmachine-db
    hostname: gifmachine-db
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gifmachine
    networks:
      - gifmachine-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  gifmachine-network:

volumes:
  gifmachine-db: